<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class project_seed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $project = [
            [
                'nama_client' => 'rama',
                'jenis'=>'AplikasiMobile',
                'nama_project' => 'Aplikasi Mobile dart flutter',
                'deskripsi' => 'pembuatan aplikasi mobile dengan dart flutter',
                'status' => 'Special',
                'pekerja'=>'["Syaiban Ahmad Ramadhan"]',
                'foto_completed' => 'imgCompleted/ramaMobile.png',
            ],
            [
                'nama_client' => 'client1',
                'jenis'=>null,
                'nama_project' => 'project1',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client2',
                'jenis'=>null,
                'nama_project' => 'project2',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client3',
                'jenis'=>null,
                'nama_project' => 'project3',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client4',
                'jenis'=>null,
                'nama_project' => 'project4',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client5',
                'jenis'=>null,
                'nama_project' => 'project5',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client6',
                'jenis'=>null,
                'nama_project' => 'project6',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client7',
                'jenis'=>null,
                'nama_project' => 'project7',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],

            [
                'nama_client' => 'client8',
                'jenis'=>null,
                'nama_project' => 'project8',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client9',
                'jenis'=>null,
                'nama_project' => 'project9',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client10',
                'jenis'=>null,
                'nama_project' => 'project10',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client11',
                'jenis'=>null,
                'nama_project' => 'project11',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client12',
                'jenis'=>null,
                'nama_project' => 'project12',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client13',
                'jenis'=>null,
                'nama_project' => 'project13',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project14',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project15',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project16',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project17',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project18',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project19',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project20',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project21',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project22',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project23',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project24',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project25',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project26',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project27',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project28',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project29',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project30',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project31',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project32',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project33',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
            [
                'nama_client' => 'client14',
                'jenis'=>null,
                'nama_project' => 'project34',
                'deskripsi' => 'pembuatan aplikasi dengan .....',
                'status' => 'Completed',
                'pekerja'=>'null',
                'pekerja'=>'["M.Syahrul Saefulah"]',
                'foto_completed' => null,
            ],
        ];
        DB::table('project')->insert($project);
    }
}
